server.port=${APP_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/chamados}
spring.datasource.username=${DB_USER:chamados_dev}
spring.datasource.password=${DB_PASSWORD:chamados_dev_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

server.servlet.jsp.init-parameters.development=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE